#!/bin/sh
sudo echo 'if_iwn_load="YES"'>> /boot/loader.conf
sudo echo 'acpi_ibm_load="YES"'>> /boot/loader.conf
sudo sysctl acpi_video_load="YES"
sudo sysrc ifconfig_iwn0="wlan0"  				# To set up wireless ethernet with Intel WiFi Cards
sudo sysrc ifconfig_wlan0="SYNCDHCP WPA"
sudo sysrc sddm_enable=YES  					# Setting up the system wide utils
sudo sysrc dbus_enable=YES
sudo sysrc kld_list="/boot/modules/i915kms.ko cuse"
cd ~/
mkdir -p ~/.local/share/fonts .config .cache .newsboat Documents Pictures Downloads Code   #home directory basics
sudo pw user mod nigel -G wheel || sudo pw user mod nigel -G video
sudo pkg install --quiet --yes gh drm-kmod i3-gaps sddm compton feh w3m-img xorg scrot polybar i3lock neofetch lynx vim feh zsh rofi ImageMagick7 py38-ranger iosevka firefox
cd ..
cp -r .config/* ~/.config/    					# More home directroy nonsense
cp -r .local/* ~/.local/
cp .Xresources ~/
cp .vimrc ~/
cd Code/
git clone https://github.com/K547NK/Elegant-sddm.git
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"  #oh-my-zsh eye candy for zsh
