#!/bin/sh
sudo pw user mod nigel -G wheel || sudo pw user mod nigel -G video
#install both display manager and server also add window manager and compositor
sudo pkg install drm-kmod i3-gaps sddm compton feh xorg scrot polybar i3lock neofetch lynx vim feh zsh rofi ImageMagick7

#details
sudo mkdir -p /usr/share/sddm/faces/ 
sudo cp -r ~/freebsd/nigel.face.icon /usr/share/sddm/faces/

mkdir ~/.config 
mkdir ~/Documents
mkdir -p ~/local/share/fonts
sudo sysrc sddm_enable=YES
sudo sysrc dbus_enable=YES
sudo sysrc kld_list="/boot/modules/i915kms.ko"
cp -r H ~/Documents/
cp -r .config/* ~/.config/
cp .Xresources ~/
cp .vimrc ~/
cp -r ~/config/polybar/fonts/* ~/.local/share/fonts
fc-cache -v
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

