#!/bin/sh
sudo pw user mod nigel -G wheel
#install both display manager and server also add window manager and compositor
sudo pkg install drm-kmod chromium i3-gaps sddm compton feh xorg hal scrot polybar i3lock neofetch lynx vim feh zsh rofi ImageMagick7

#details
sudo mkdir -p /usr/share/sddm/faces/ 
sudo cp -r ~/freebsd/nigel.face.icon /usr/share/sddm/faces/

mkdir ~/.config 
mkdir ~/Documents

cp -r H ~/Documents/
cp -r .config/* ~/.config/
cp .Xresources ~/
cp .vimrc ~/
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

sudo echo 'hald_enable="YES"' > /etc/rc.conf 
sudo echo 'dbus_enable="YES"' > /etc/rc.conf 
sudo echo 'sddm_enable="YES"' > /etc/rc.conf 
sudo echo 'kld_list="/boot/modules/amdgpu.ko"' > /etc/rc.conf 
sudo echo 'hw.syscons.disable=1' > /boot/loader.conf


