#!/bin/bash
pkill polybar
if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    MONITOR=$m polybar --reload right & MONITOR=$m polybar --reload center & MONITOR=$m polybar --reload left &
  done
else
  polybar --reload right & polybar --reload left & polybar --reload center &
fi
